# Configuration for commitlint
# This ensures commit messages follow conventional commit format
# https://www.conventionalcommits.org/

extends:
  - "@commitlint/config-conventional"

rules:
  # Allow longer header lines
  header-max-length: [2, "always", 100]
  
  # Types allowed in commit messages
  type-enum:
    - 2
    - always
    -
      - feat      # New feature
      - fix       # Bug fix
      - docs      # Documentation changes
      - style     # Code style changes (formatting, etc)
      - refactor  # Code refactoring
      - perf      # Performance improvements
      - test      # Adding or updating tests
      - build     # Build system changes
      - ci        # CI configuration changes
      - chore     # Other changes that don't modify src or test files
      - revert    # Reverting a previous commit
